# Generated by Django 4.2.7 on 2023-12-03 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('denis_rest', '0002_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='foto/default.jpg', upload_to='foto'),
        ),
    ]
